### ISSUE TITLE
Menu visibility problem after window resize

### ISSUE THREAD

**Issue by pavelcalvera** [KnivesTix/wow#1]
I've noticed that menu starts to behave wrong if you resize browser window to see swap menu trigger link (I'll call it "swap"). Here are steps to see that buggy behavior:
- resize window horizontally until swap is shown
- click it to see the menu
- resize back to full width and then back to see the swap again - you'll see that menu is visible at the same time when you see the swap
- click the swap to hide the menu and resize browser window back to the full width - you'll see that there is no menu shown... and no swap as well.

**Comment by KnivesTix** [comment]
Oh yeah. I know about this error. But I don't know how to fix it yet
